"""empty message

Revision ID: 9a106b6090ae
Revises: 
Create Date: 2022-04-21 02:13:48.855099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a106b6090ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starship',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.String(), nullable=False),
    sa.Column('starship_class', sa.String(), nullable=False),
    sa.Column('consumables', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('crew', sa.String(), nullable=False),
    sa.Column('passengers', sa.String(), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('s2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s2',
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cargo_capacity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('starship_class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('consumables', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manufacter', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('crew', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nature', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='starship_pkey1')
    )
    op.drop_table('starship')
    # ### end Alembic commands ###
